# Site settings
author: Dillorom Abdulloeva
title: MeCoding
header-img: img/home-bg.png
email: dabdulloeva@gmail.com
copyright_name: Dillorom Abdulloeva
description: > # this means to ignore newlines until "baseurl:"
  Learn coding with me
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dillorom

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
